name: Mirror to Codeberg

on:
  push:
    branches: [ main ]
  delete:

jobs:
  mirror_to_codeberg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: wearerequired/git-mirror-action@v1
        with:
          source-repo: "https://github.com/${{ github.repository }}.git"
          # PASSE DIE NÃ„CHSTE ZEILE AN:
          destination-repo: "https://codeberg.org/${{ github.repository }}.git"
        env:
          GIT_USERNAME: "JumpStone"
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}